title: Gradient Dude
title_image: /assets/images/gradient_dude_logo_banks_sans2_square_larger_font_256.png
name: Gradient Dude Blog
author: Artsiom Sanakoyeu
profile_url:  https://gdude.de
twitter_username: artsiom_s
baseurl: "/blog"
description: >- # this means to ignore newlines until "baseurl:"
 My thoughts on Machine Learning, Computer Vision and Programming.

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
permalink:  /:year-:month-:day/:title
